name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - run: npm build
      - run: npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out